package com.nebras.mobile.core.util

/**
 * نصوص التطبيق العربية للمفاتيح الديناميكية.
 *
 * بعد التعريب الكامل (إزالة easy_localization) بقيت مواضع قليلة تُمرَّر
 * فيها المفاتيح عبر متغيّرات وقت التشغيل (أسباب البلاغ، أخطاء الدخول،
 * رسائل التنزيل…) فلا يمكن استبدالها بنصّ حرفيّ. الامتداد [ar]
 * يحلّها من هذه الخريطة، ويعيد النص نفسه إن لم يكن مفتاحاً معروفاً.
 */
object ArStrings {
    val arDynamic: Map<String, String> = mapOf(
        "No" to "لا",
        "Yes" to "نعم",
        "Back" to "رجوع",
        "Go" to "اذهب",
        "Share" to "مشاركة",
        "Theme" to "المظهر",
        "System" to "تلقائي (النظام)",
        "Dark" to "داكن",
        "Light" to "فاتح",
        "Enable" to "تفعيل",
        "Refresh" to "تحديث",
        "Sleep" to "مؤقّت النوم",
        "Buffering..." to "جارٍ التحميل…",
        "Turn off" to "إيقاف",
        "Available offline" to "متاح دون إنترنت",
        "Playback speed" to "سرعة التشغيل",
        "Sleep timer" to "مؤقّت النوم",
        "Go to page" to "اذهب إلى صفحة",
        "{} min" to "{} دقيقة",
        "Pause (long-press to cancel)" to "إيقاف مؤقّت (اضغط مطوّلاً للإلغاء)",
        "Cancel Download" to "إلغاء التحميل",
        "Stop and discard this download?" to "إيقاف هذا التحميل وحذفه؟",
        "Could not open this document" to "تعذّر فتح هذا المستند",
        "The file may be corrupted or unavailable." to "قد يكون الملفّ تالفاً أو غير متاح.",
        "Failed to load notifications" to "تعذّر تحميل الإشعارات",
        "Notifications are disabled in system settings" to "الإشعارات معطّلة في إعدادات النظام",
        "No content yet. Pull down to refresh." to "لا يوجد محتوى بعد. اسحب للأسفل للتحديث.",
        "Back to welcome" to "العودة إلى شاشة الترحيب",
        "video_playback_error" to "حدث خطأ أثناء تشغيل الفيديو. تحقّق من اتصالك وحاول مجدداً.",
        "media_access_denied" to "هذا الملفّ غير متاح حاليًا من المصدر (مقيَّد من قِبَل الخادم). جرّب عنصرًا آخر من نفس المجموعة.",
        "media_not_found" to "تعذّر العثور على هذا الملفّ على الخادم البعيد (قد يكون حُذف أو نُقل).",
        "You may also like" to "قد يعجبك أيضًا",
        "Most Watched" to "الأكثر مشاهدة",
        "Video" to "فيديو",
        "Videos" to "فيديوهات",
        "Audio" to "صوت",
        "Audios" to "صوتيات",
        "Book" to "كتاب",
        "Books" to "كتب",
        "video" to "فيديو",
        "audio" to "صوت",
        "book" to "كتاب",
        "youtube" to "فيديو يوتيوب",
        "Good Morning" to "صباح الخير",
        "Good Afternoon" to "مساء الخير",
        "Good Evening" to "مساء الخير",
        "☀️" to "☀️",
        "👋" to "👋",
        "🌙" to "🌙",
        "Explore the archives of knowledge" to "تصفّح أرشيف المعرفة",
        "Restricted Area" to "منطقة محظورة",
        "This section is reserved for administrators only." to "هذا القسم مخصص للمسؤولين فقط.",
        "Cancel" to "إلغاء",
        "Continue" to "متابعة",
        "Read" to "قراءة",
        "Download" to "تحميل",
        "Download Failed" to "فشل التحميل",
        "Delete Download" to "حذف التحميل",
        "Remove downloaded file?" to "حذف الملف المحمّل؟ يمكنك إعادة تحميله لاحقاً.",
        "Delete" to "حذف",
        "Pause" to "إيقاف مؤقت",
        "Resume" to "استئناف",
        "Retry" to "إعادة المحاولة",
        "Downloading..." to "جاري التحميل...",
        "Downloaded" to "تم التحميل",
        "Book Details" to "تفاصيل الكتاب",
        "Settings" to "الإعدادات",
        "Dark Mode" to "الوضع الداكن",
        "Push Notifications" to "الإشعارات الفوريّة",
        "Undo" to "تراجع",
        "About" to "حول",
        "Home" to "الرئيسية",
        "Saved" to "المحفوظات",
        "Notifications" to "الإشعارات",
        "Menu" to "القائمة",
        "Privacy Policy" to "سياسة الخصوصية",
        "Filters" to "التصفية",
        "Continue as guest" to "المتابعة كضيف",
        "Guest" to "ضيف",
        "Guest mode" to "وضع الضيف",
        "Signed in" to "مسجّل الدخول",
        "guest_prompt_message" to "أنشئ حساباً ليُخصِّص لك التطبيق تجربته باحتراف: توصيات تناسبك، ومتابعة ما بدأته، ومزامنة مفضّلاتك.",
        "guest_prompt_action" to "إنشاء حساب",
        "guest_prompt_dismiss" to "لاحقاً",
        "account_title" to "حسابي",
        "account_details" to "بيانات الحساب",
        "account_name" to "الاسم",
        "account_email" to "البريد الإلكتروني",
        "account_id" to "معرّف الحساب",
        "account_signed_in_at" to "تاريخ الدخول",
        "account_data_note" to "يخزّن التطبيق مفضّلتك وسجلّ مشاهدتك على جهازك فقط. لا نحفظ بيانات شخصيّة على خوادمنا عدا بلاغات المحتوى التي ترسلها (إن أرسلت)، وتُحذف عند حذف حسابك. حذف الحساب يزيل هويّتك ويمسح بياناتك المحليّة نهائيّاً.",
        "account_sign_out" to "تسجيل الخروج",
        "account_delete" to "حذف الحساب",
        "account_delete_confirm_title" to "حذف الحساب نهائيّاً؟",
        "account_delete_confirm_body" to "سيُحذف حسابك وتُمسح كل بياناتك المحليّة (المفضّلة، سجلّ المشاهدة، الاهتمامات) نهائيّاً ولا يمكن التراجع.",
        "account_deleted" to "تم حذف الحساب",
        "account_delete_failed" to "تعذّر حذف الحساب. حاول مجدّداً.",
        "account_guest_note" to "أنت تتصفّح كضيف بلا حساب. أنشئ حساباً للحصول على تجربة مخصّصة ومزامنة.",
        "report_button" to "إبلاغ",
        "report_sheet_title" to "الإبلاغ عن هذا المحتوى",
        "report_submitted" to "تمّ إرسال البلاغ. شكراً لك.",
        "report_submitted_title" to "تمّ استلام بلاغك",
        "report_submitted_body" to "شكراً لك. سنراجع البلاغ يدوياً، وإذا ثبتت مخالفة المحتوى فسنزيله نهائيّاً من قاعدة بياناتنا خلال 24 ساعة كحدّ أقصى. وفي جميع الأحوال، لن يظهر لك هذا المحتوى بعد الآن.",
        "report_failed" to "تعذّر إرسال البلاغ. حاول مجدّداً.",
        "ok" to "حسناً",
        "attribution_source" to "المصدر",
        "attribution_license" to "الرخصة",
        "report_reason_copyright" to "ينتهك ملكية فكرية / حقوق نشر",
        "report_reason_sexual" to "محتوى جنسيّ صريح",
        "report_reason_child_safety" to "يضرّ بالأطفال",
        "report_reason_violence" to "عنف",
        "report_reason_terrorism" to "إرهاب أو تطرّف",
        "report_reason_other" to "أخرى",
        "content_policy_title" to "سياسة المحتوى",
        "content_policy_text" to "نبراس منصّة محتوى موسوعيّ معرفيّ عامّ. لا ننشر عمداً أيّ محتوى ينتهك حقوق الملكية الفكرية أو حقوق النشر، ولا أيّ محتوى جنسيّ صريح أو يضرّ بالأطفال أو يحضّ على العنف أو الإرهاب. كلّ المحتوى يُفترض أن يكون عامّاً أو مرخّصاً. إن صادفت مخالفة، استخدم زرّ «إبلاغ» على المحتوى وسنراجعها ونزيلها فوراً عند ثبوتها.",
        "content_section_label" to "القسم",
        "Offline banner" to "أنت غير متصل — تُعرض نسخة محفوظة من المحتوى.",
        "No Content Available" to "لا يوجد محتوى متاح",
        "Failed to load video" to "فشل تحميل الفيديو",
        "Failed to load audio" to "فشل تحميل الصوت",
        "Search" to "بحث",
        "Search by title, category, or type..." to "ابحث بالعنوان أو الفئة أو النوع...",
        "No results found" to "لم يتم العثور على نتائج",
        "Try adjusting your search" to "حاول تعديل بحثك",
        "You may also watch" to "قد يعجبك أيضاً",
        "Something went wrong" to "حدث خطأ ما",
        "No content available" to "لا يوجد محتوى متاح",
        "No content in this section" to "لا يوجد محتوى داخل هذا القسم",
        "No subsections available" to "لا توجد أقسام فرعية داخل هذا القسم",
        "No secondary sections available" to "لا توجد أقسام ثانوية داخل هذا القسم الفرعي",
        "Saved Content" to "المحتوى المحفوظ",
        "Removed from saved" to "تمت الإزالة من المحفوظات",
        "Save" to "حفظ",
        "Remove from saved" to "إزالة من المحفوظات",
        "Added to saved" to "تمت الإضافة إلى المحفوظات",
        "saved_done" to "محفوظ",
        "Favorite" to "مُفضّلة",
        "No downloads yet" to "لا توجد تنزيلات بعد",
        "Download deleted" to "حُذف التنزيل",
        "Notification deleted" to "تم حذف الإشعار",
        "Clear all" to "مسح الكل",
        "Delete all notifications?" to "حذف جميع الإشعارات؟",
        "No notifications available" to "لا توجد إشعارات",
        "No saved content yet" to "لا يوجد محتوى محفوظ بعد",
        "Search content..." to "ابحث عن محتوى...",
        "Download the book first to read offline" to "حمّل الكتاب أولاً للقراءة بدون اتصال",
        "Our Mission" to "رسالتنا",
        "Version" to "الإصدار",
        "Search for videos, audio, and books" to "ابحث عن فيديوهات وصوتيات وكتب",
        "Recent Searches" to "عمليات البحث الأخيرة",
        "Recent searches" to "عمليات البحث الأخيرة",
        "No recent searches" to "لا توجد عمليات بحث سابقة",
        "Clear" to "مسح",
        "Remove" to "إزالة",
        "Downloads" to "التحميلات",
        "اقتراحات قد تعجبك" to "اقتراحات قد تعجبك",
        "الرئيسية" to "الرئيسية",
        "ابحث عن محتوى يعجبك لتساعدنا في إنشاء صفحة مخصصة لك" to "ابحث عن محتوى يعجبك لتساعدنا في إنشاء صفحة مخصصة لك",
        "تعذر الوصول إلى المحتوى. تأكد من تسجيل الدخول." to "تعذر الوصول إلى المحتوى. تأكد من تسجيل الدخول.",
        "عذراً، حدث خطأ في الاتصال بالشبكة." to "عذراً، حدث خطأ في الاتصال بالشبكة.",
        "إعادة المحاولة" to "إعادة المحاولة",
        "هذا المحتوى غير متوفر بدون إنترنت" to "هذا المحتوى غير متوفر بدون إنترنت",
        "Closest matches" to "أقرب النتائج",
        "Popular picks" to "اختيارات شائعة",
        "We did not find an exact match, but here is the closest." to "لم نعثر على تطابق تامّ، لكن هذه أقرب النتائج.",
        "Try something popular while you refine your search." to "جرّب شيئًا شائعًا ريثما تُصقل كلمات بحثك.",
        "All" to "الكل",
        "Section" to "القسم",
        "Apply Filters" to "تطبيق",
        "Clear All" to "مسح الكل",
        "Content Type" to "نوع المحتوى",
        "You May Also Read" to "قد يعجبك أيضاً",
        "Read more" to "اقرأ المزيد",
        "Show less" to "عرض أقل",
        "No source available" to "لا يوجد مصدر متاح",
        "Description" to "الوصف",
        "video_unavailable" to "المحتوى غير متاح حالياً",
        "Audio unavailable" to "الصوت غير متاح حالياً",
        "No description available yet." to "لا يوجد وصف متاح بعد.",
        "Nebras" to "نبراس",
        "Content" to "المحتوى",
        "Initializing audio..." to "جاري تهيئة الصوت...",
        "Switch to horizontal" to "عرض أفقي",
        "Switch to vertical" to "عرض عمودي",
        "Night mode" to "الوضع الليلي",
        "Day mode" to "الوضع النهاري",
        "Content not available yet" to "المحتوى غير متاح بعد",
        "Search in book" to "ابحث في الكتاب",
        "Page {} of {}" to "الصفحة {} من {}",
        "Loading..." to "جار التحميل...",
        "Just now" to "الآن",
        "{} minutes ago" to "منذ {} دقيقة",
        "{} hours ago" to "منذ {} ساعة",
        "{} days ago" to "منذ {} يوم",
        "Grid view" to "عرض شبكة",
        "List view" to "عرض قائمة",
        "Switch layout" to "تبديل طريقة العرض",
        "main" to "قسم رئيسي",
        "sub" to "قسم فرعي",
        "secondary" to "قسم ثانوي",
        "For You" to "لك",
        "Discover personalized content" to "مقترحات مخصّصة حسب ما تشاهده وتستمع إليه وتقرؤه",
        "Shuffle" to "خلط",
        "No personalized content yet" to "لا توجد مقترحات بعد. تصفّح المحتوى قليلاً ثم عُد إلى هنا.",
        "Welcome greeting" to "بوّابتك إلى المعرفة العامة",
        "Welcome to Nebras" to "مرحباً بك في تطبيق نبراس",
        "Welcome subtitle" to "منصّتك الرقمية للمحتوى المصوَّر والمسموع والمكتوب. أنشئ حسابك أو سجّل دخولك للبدء.",
        "Create account" to "إنشاء حساب",
        "Sign in" to "تسجيل الدخول",
        "Continue with Google hint" to "الدخول عبر حساب Google الموجود على هذا الجهاز",
        "Browse without account" to "تصفّح بدون حساب",
        "Create your account" to "إنشاء حسابك",
        "Welcome back" to "مرحباً بعودتك",
        "Signup subtitle" to "اختر حساب Google من هذا الجهاز لإنشاء حساب نبراس الخاص بك والاستمتاع بمحتوى مخصّص.",
        "Signin subtitle" to "اختر حساب Google المستخدم سابقاً للدخول إلى نبراس واستعادة بياناتك.",
        "Sign up with Google" to "التسجيل عبر Google",
        "Sign in with Google" to "الدخول عبر Google",
        "Privacy note" to "نستخدم حساب Google للتعرّف على هويتك فقط. لن نتلقّى كلمة المرور ولن نشارك أي بيانات شخصية.",
        "Sign out" to "تسجيل الخروج",
        "Sign out confirm" to "هل تريد تسجيل الخروج من حسابك في نبراس؟",
        "Confirm" to "تأكيد",
        "Auth error network" to "لا يوجد اتصال بالإنترنت. يرجى التحقق من الشبكة والمحاولة مجدداً.",
        "Auth error canceled" to "تم إلغاء عملية الدخول.",
        "Auth error sign_in_failed" to "تعذّر الوصول إلى خدمة Google للدخول الآن. يرجى المحاولة بعد قليل.",
        "React" to "تفاعل",
        "Comment" to "تعليق",
        "Comments" to "التعليقات",
        "Comments count" to "{n} تعليق",
        "Reactions" to "التفاعلات",
        "People reacted" to "{n} شخصاً تفاعلوا",
        "Be the first to react" to "كن أوّل من يتفاعل مع هذا المحتوى.",
        "Comments and reactions" to "التعليقات والتفاعلات",
        "Be the first to comment" to "كن أوّل من يعلّق على هذا المحتوى.",
        "Write a comment" to "اكتب تعليقاً...",
        "Sign in to comment" to "سجّل الدخول لتتمكّن من التعليق.",
        "Comment post failed" to "تعذّر نشر التعليق. يرجى المحاولة مجدّداً.",
        "Anonymous" to "مستخدم",
        "Minimize" to "تصغير",
        "No internet connection" to "لا يوجد اتصال بالإنترنت",
        "Mobile data" to "بيانات الجوّال",
        "You are on mobile data. Download anyway?" to "أنت على بيانات الجوّال — هل تريد التنزيل؟",
        "onboarding_title_1" to "اكتشف المعرفة",
        "onboarding_desc_1" to "تصفّح محتوى موسوعيّاً متنوّعاً: كتب ومقاطع صوتية وفيديو في مكان واحد.",
        "onboarding_title_2" to "أينما كنت",
        "onboarding_desc_2" to "نزّل ما يعجبك واستمع واقرأ دون اتصال بالإنترنت.",
        "onboarding_title_3" to "احفظ وتابع",
        "onboarding_desc_3" to "احفظ ما يعجبك بنقرة في «المحفوظات»، وتابع من حيث توقّفت في الكتب والصوت والفيديو.",
        "Skip" to "تخطٍّ",
        "Next" to "التالي",
        "Get started" to "ابدأ الآن",
        "Minutes ago" to "قبل {n} دقيقة",
        "Hours ago" to "قبل {n} ساعة",
        "Days ago" to "قبل {n} يوم",
        "Delete comment" to "حذف التعليق",
        "Delete comment confirm" to "هل تريد حذف هذا التعليق نهائيّاً؟",
        "home_rail_newest" to "الجديد في نبراس",
        "home_rail_popular" to "الأكثر مشاهدة",
        "home_rail_for_you" to "مقترَح لك",
        "home_rail_search" to "من اهتماماتك في البحث",
        "home_rail_search_prefix" to "من اهتماماتك",
        "home_rail_continue" to "تابع التصفّح",
        "home_rail_browse_sections" to "تصفّح الأقسام",
        "home_rail_view_all" to "اعرض الكلّ",
        "forget_interests_title" to "نسيان اهتماماتي",
        "forget_interests_subtitle" to "يمسح التوصيات والبحث المحلي فقط",
        "forget_interests_confirm" to "سيتم حذف ملفّ الاهتمامات وسجلّ السلوك و«تابع التصفّح» من هذا الجهاز. العدّادات العامّة على الخادم لا تتأثّر. هل تريد المتابعة؟",
        "forget_interests_done" to "تم مسح بيانات التخصيص المحليّة.",
        "Play" to "تشغيل",
        "Close" to "إغلاق",
        "Loading video…" to "جارٍ تحميل الفيديو…",
        "Next video in {} s" to "الفيديو التالي خلال {} ث",
        "home_access_error" to "تعذر الوصول إلى المحتوى. تأكد من تسجيل الدخول.",
        "home_generic_error" to "عذراً، حدث خطأ في الاتصال بالشبكة.",
        "download_error_network" to "تعذّر التنزيل: مشكلة في الاتصال بالشبكة. تحقّق من اتصالك وحاول مجدداً.",
        "download_error_timeout" to "انتهت مهلة التنزيل. تحقّق من اتصالك وحاول مجدداً.",
        "download_error_storage" to "لا توجد مساحة تخزين كافية أو التخزين غير متاح. حرّر مساحة وحاول مجدداً.",
        "download_error_generic" to "تعذّر التنزيل. حاول مجدداً.",
        "Swipe to delete" to "اسحب للحذف",
        "suggest_button" to "اقترح تصحيحاً",
        "suggest_title" to "اقترح تصحيحاً ✏️",
        "suggest_hint" to "عنوان خاطئ؟ ملف لا يعمل؟ تصنيف غير مناسب؟ اكتب ملاحظتك…",
        "suggest_send" to "إرسال",
        "suggest_sent" to "شكراً! وصل اقتراحك للمشرفين 💚",
        "suggest_failed" to "تعذّر الإرسال — حاول مجدداً.",
        "share_button" to "مشاركة",
        "section_follow" to "تابع هذا القسم",
        "section_unfollow" to "إلغاء متابعة القسم",
        "section_follow_on" to "ستصلك إشعارات الجديد في «{name}» 🔔",
        "section_follow_off" to "أُلغيت متابعة «{name}»",
        "daily_pick_title" to "اكتشف اليوم",
        "daily_pick_open" to "اضغط للاستكشاف ←",
        "deeplink_not_found" to "المحتوى غير متاح حالياً — افتح التطبيق وحدّث الرئيسية.",
        "cancel" to "إلغاء",
        "ugc_badge" to "من المجتمع",
        "ugc_community_title" to "مجتمع نبراس",
        "ugc_fab_label" to "انشر",
        "ugc_community_disclaimer" to "محتوى ينشره مستخدمون مستقلون في قنواتهم الخاصة، ولا يمثّل إدارة نبراس ولا تتحمّل نبراس مسؤوليته. الإبلاغ متاح على كل منشور.",
        "ugc_my_sections_title" to "أقسام قناتك",
        "ugc_my_sections_hint" to "نظّم قناتك بأقسام تسمّيها بنفسك (اختياري تماماً) — لا علاقة لها بأقسام نبراس الرسمية.",
        "ugc_my_sections_publish_hint" to "اختر قسماً من أقسام قناتك أو انشر بدون قسم — الأمر لك بالكامل.",
        "ugc_my_section_new" to "قسم جديد في قناتك",
        "ugc_my_section_name" to "اسم القسم",
        "ugc_my_section_add" to "إضافة قسم",
        "ugc_no_section" to "بدون قسم",
        "ugc_community_empty" to "لا توجد منشورات من المجتمع بعد. كن أول من يشارك معرفة نافعة.",
        "ugc_channel" to "القناة",
        "ugc_channel_not_found" to "هذه القناة لم تعد متاحة.",
        "ugc_channel_posts" to "منشورات القناة",
        "ugc_channel_empty" to "لا توجد منشورات في هذه القناة بعد.",
        "ugc_edit_channel" to "تعديل القناة",
        "ugc_channel_name" to "اسم القناة",
        "ugc_channel_name_hint" to "مثل: الحسّاني أو اسمك",
        "ugc_channel_name_too_short" to "اكتب اسماً للقناة من 3 أحرف على الأقل.",
        "ugc_channel_bio" to "نبذة عن القناة (اختياري)",
        "ugc_channel_section_title" to "الأقسام المرتبطة",
        "ugc_channel_section_hint" to "اختر موقعاً مناسباً من شجرة الأقسام؛ تظهر الأسماء فقط، حتى الأقسام غير العامة.",
        "ugc_channel_pick_section" to "اختر قسماً رئيسياً على الأقل.",
        "ugc_channel_save_failed" to "تعذّر حفظ القناة. حاول مجدداً.",
        "ugc_channel_suspended" to "هذه القناة موقوفة حالياً ولا يمكن النشر منها.",
        "ugc_create_channel" to "أنشئ قناتك",
        "ugc_create_channel_intro" to "أنشئ قناة باسمك لتشارك محتوى صوتياً أو مرئياً أو كتباً أو مقالات. قناتك مستقلة تماماً: تنظّمها بأقسامك الخاصة وتنشر فيها ما تشاء ضمن شروط النشر، ويظهر اسمك كناشر مستقل.",
        "ugc_create_channel_cta" to "إنشاء القناة",
        "ugc_save_channel_cta" to "حفظ التعديلات",
        "ugc_publish_title" to "نشر في المجتمع",
        "ugc_publish_cta" to "نشر الآن",
        "ugc_publish_disclaimer" to "ينشر المحتوى فوراً باسم قناتك. يمكن حذف المنشور أو القناة عند مخالفة شروط النشر.",
        "ugc_publish_failed" to "تعذّر نشر المحتوى. تحقق من الاتصال وحاول مجدداً.",
        "ugc_published" to "تم نشر محتواك في مجتمع نبراس.",
        "ugc_open_failed" to "تعذّر فتح مساحة النشر. حاول مجدداً.",
        "ugc_publishing_as" to "تنشر باسم: {name}",
        "ugc_type_audio" to "صوت",
        "ugc_type_video" to "فيديو",
        "ugc_type_book" to "كتاب PDF",
        "ugc_type_article" to "مقال",
        "ugc_pick_file" to "اختر ملفاً",
        "ugc_file_too_large" to "حجم الملف أكبر من الحد المسموح (300 م.ب).",
        "ugc_content_title" to "عنوان المحتوى",
        "ugc_content_description" to "وصف مختصر (اختياري)",
        "ugc_article_body" to "نص المقال",
        "ugc_uploading" to "جارٍ الرفع… {p}%",
        "ugc_terms_title" to "شروط النشر والخصوصية",
        "ugc_terms_link" to "اقرأ الشروط",
        "ugc_terms_intro" to "قبل النشر، تأكد أنك تملك حق مشاركة المحتوى وأنه مناسب لمجتمع نبراس.",
        "ugc_terms_warning" to "المحتوى المخالف قد يُحذف بلا إشعار، وقد تُوقَف القناة عند تكرار المخالفة.",
        "ugc_terms_accept" to "أوافق وأتابع",
        "ugc_terms_close" to "إغلاق",
        "ugc_terms_p1" to "أنشر فقط ما تملكه أو لديك إذن صريح بمشاركته.",
        "ugc_terms_p2" to "يُمنع انتهاك حقوق المؤلف أو العلامات التجارية أو الخصوصية.",
        "ugc_terms_p3" to "يُمنع المحتوى الجنسي أو الاستغلالي أو الذي يعرّض الأطفال للخطر.",
        "ugc_terms_p4" to "يُمنع التحريض على الكراهية أو العنف أو الإرهاب أو الأنشطة غير القانونية.",
        "ugc_terms_p5" to "لا تنشر بيانات شخصية أو صوراً أو تسجيلات للآخرين من دون موافقتهم.",
        "ugc_terms_p6" to "لا تستخدم القناة للخداع أو الاحتيال أو الرسائل المزعجة أو التضليل.",
        "ugc_terms_p7" to "اكتب معلومات دقيقة، وضع وصفاً واضحاً للمحتوى الذي تشاركه.",
        "ugc_terms_p8" to "يمكن للمستخدمين الإبلاغ عن المحتوى وحجب الناشر، وتراجع الإدارة البلاغات وتحذف المخالف.",
        "ugc_post_title" to "منشور المجتمع",
        "ugc_publisher_note" to "منشور من مستخدم مستقل، وليس من إدارة نبراس.",
        "ugc_open_content" to "فتح المحتوى",
        "ugc_description" to "الوصف",
        "ugc_comments" to "التعليقات",
        "ugc_no_comments" to "لا توجد تعليقات بعد.",
        "ugc_comment_hint" to "اكتب تعليقاً محترماً…",
        "ugc_comment_requires_account" to "سجّل الدخول لإضافة تعليق.",
        "ugc_comment_failed" to "تعذّر نشر التعليق. حاول مجدداً.",
        "ugc_block_channel_title" to "حجب القناة؟",
        "ugc_block_channel_body" to "لن تظهر لك منشورات «{name}» على هذا الجهاز.",
        "ugc_block_cta" to "حجب القناة",
        "ugc_channel_blocked" to "تم حجب القناة من موجزك.",
        "ugc_delete_post_title" to "حذف المنشور؟",
        "ugc_delete_post_body" to "سيُحذف المنشور وملفه نهائياً.",
        "ugc_delete_cta" to "حذف المنشور",
        "ugc_main_section" to "القسم الرئيسي",
        "ugc_sub_section" to "القسم الفرعي",
        "ugc_secondary_section" to "القسم الثانوي",
        "ugc_none" to "بدون اختيار",
        "ugc_no_suitable_section" to "لا أجد قسماً مناسباً",
        "ugc_sections_load_error" to "تعذّر تحميل الأقسام. تحقق من اتصالك وحاول مجدداً.",
        "ugc_request_section_title" to "اقترح قسماً جديداً",
        "ugc_request_section_hint" to "يرسل الاقتراح إلى الإدارة؛ لا يُنشئ قسماً عاماً تلقائياً.",
        "ugc_request_section_name" to "اسم القسم المقترح",
        "ugc_request_section_note" to "ملاحظة للإدارة (اختياري)",
        "ugc_request_section_send" to "إرسال الاقتراح",
        "ugc_request_section_sent" to "وصل اقتراح القسم إلى الإدارة.",
        "ugc_requires_account_title" to "سجّل الدخول للنشر",
        "ugc_requires_account_body" to "إنشاء قناة أو نشر محتوى يحتاج حساباً حتى يظهر اسم الناشر وتبقى المنصة آمنة.",
        "ugc_sign_in_cta" to "الدخول عبر Google",
        "ugc_sign_in_failed" to "تعذّر تسجيل الدخول. حاول مجدداً.",
    )

    /** يحلّ المفتاح إلى نصّه العربيّ، أو يعيده كما هو إن لم يكن معروفاً. */
    fun resolve(key: String): String = arDynamic[key] ?: key
}

/**
 * نظير امتداد `ArText.ar` على String في Dart.
 * الاستعمال مطابق: `"report_failed".ar`.
 */
val String.ar: String
    get() = ArStrings.arDynamic[this] ?: this
